#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 BUILDING your project before committing👷‍♂️🏗️'
echo 'please be patient, this may take a while...'

# shellcheck disable=SC2015
yarn build ||
(
    echo '🔨❌ Yoo, you have a problem in your code. Check your build 😶‍🌫️😶‍🌫🔨❌
          Run yarn build, add changes and try commit again.';
    false;
)

echo '🎉 No error found: committing this now.... ✨🚀🏄‍♂️🍻'
