#!/usr/bin/env sh


. "$(dirname -- "$0")/_/husky.sh"

yarn lint && yarn test:typecheck && yarn prettier:write && yarn prettier:check

if [ $? -eq 0 ]; then
  echo -e "\033[32mProject Linted Correctly
  |\---/|
  | o_o |
   \_^_/ \033[0m"
else
  echo -e "\033[31mERROR: Something went wrong\033[0m"
fi
